language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - python setup.py develop

before_script:
  - source flaskie/.travis.sh
  - psql -c "create database flaskie_test;" -U postgres
  - psql -c "create user asheuh with password 'mermaid';" -U postgres

script:
  - py.test --cov=flaskie tests/

after_success:
  - coveralls
